
import { ServiceItem, CategoryTab } from './types';

export const CATEGORIES: CategoryTab[] = [
  { id: '전체', label: '전체' },
  { id: '채널', label: '채널Agent' },
  { id: '보험금', label: '보험금심사Agent' },
  { id: '대고객', label: '대고객 Agent' },
  { id: '경영지원', label: '경영지원Agent' },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'wiz',
    title: 'AI 지식검색',
    description: '질병별 보장정보와 설계 인사이트를 확인하세요. 약관 및 특약 조회도 가능해요',
    category: '채널',
    tags: ['간편 언더라이팅', '약관', '특약'],
    provider: 'GA영업추진P',
    userCount: '900명',
  },
  {
    id: '1',
    title: 'GFC AI써치',
    description: 'GFC 영업 활동을 지원하는 지능형 검색 서비스입니다. 기업현황 요약 및 영업 포인트를 제공합니다.',
    category: '채널',
    tags: ['기업요약', '영업포인트'],
    provider: 'GFC영업추진P',
    userCount: '1,800명',
  },
  {
    id: '5',
    title: '보험상품 비교',
    description: '최적의 보험 상품을 한눈에 비교해주는 지능형 큐레이션 서비스입니다. 장단점을 요약해 드려요.',
    category: '채널',
    tags: ['상품비교', '장단점요약'],
    provider: 'AI지원P',
    userCount: '3,100명',
  },
  {
    id: '4',
    title: 'AI CX글쓰기',
    description: '고객 경험을 혁신하는 AI 기반 맞춤형 콘텐츠 작성 도구입니다. 언어교정과 톤앤매너를 지원합니다.',
    category: '대고객',
    tags: ['언어교정', '톤앤매너'],
    provider: '고객경험혁신P',
    userCount: '950명',
  },
  {
    id: '3',
    title: 'AI지급심사',
    description: '보험금 지급 심사 효율을 높이는 AI 기반 전문 심사 도구입니다. 검색 효율화를 지원합니다.',
    category: '보험금',
    tags: ['지급심사', '검색효율'],
    provider: '심사지원P',
    userCount: '1,200명',
  },
  {
    id: '6',
    title: '재무심사Agent',
    description: '복잡한 재무 데이터 분석과 심사를 돕는 AI 에이전트입니다. 심사 근거를 요약해 드립니다.',
    category: '경영지원',
    tags: ['데이터분석', '심사요약'],
    provider: '재무심사P',
    userCount: '600명',
  },
  {
    id: '2',
    title: 'VOC 지식검색',
    description: '고객의 소리와 다양한 지식 베이스를 통합 탐색하는 검색 엔진입니다. VOC를 심층 분석합니다.',
    category: '대고객',
    tags: ['VOC분석', '통합검색'],
    provider: 'GA영업지원P',
    userCount: '2,100명',
  },
  {
    id: '7',
    title: '광고심의 Agent',
    description: '광고 제작물의 규정 준수 여부를 자동으로 검토하는 심의 도구입니다. 법규 및 사규를 판별합니다.',
    category: '경영지원',
    tags: ['법규', '사규판별'],
    provider: '준법감시P',
    userCount: '450명',
  },
  {
    id: '8',
    title: '정보보호QA',
    description: '정보보호 정책 및 가이드라인에 대한 지능형 질의응답 서비스입니다. 보안 가이드를 제공합니다.',
    category: '경영지원',
    tags: ['정책가이드', '보안QA'],
    provider: '정보보호P',
    userCount: '800명',
  },
];
